version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jvc-essentials-dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      # Prevent overwriting node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm run dev --host
    profiles:
      - dev

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jvc-essentials-prod
    ports:
      - "6000:80"
    restart: unless-stopped
    profiles:
      - prod
